# Generated by Django 5.2.1 on 2025-06-06 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StorageArea",
            fields=[
                (
                    "location_code",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("type", models.CharField(max_length=10)),
                ("description", models.TextField()),
                ("manager", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "storage_area",
            },
        ),
        migrations.CreateModel(
            name="WarehouseOperations",
            fields=[
                (
                    "operation_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("type", models.CharField(max_length=10)),
                ("related_order", models.CharField(max_length=8)),
                ("operator", models.CharField(max_length=8)),
                ("time", models.DateTimeField()),
                ("remark", models.TextField()),
            ],
            options={
                "db_table": "warehouse_operations",
            },
        ),
        migrations.CreateModel(
            name="WarehouseStock",
            fields=[
                ("product_id", models.CharField(max_length=8)),
                (
                    "batch_id",
                    models.CharField(max_length=12, primary_key=True, serialize=False),
                ),
                ("quantity", models.FloatField()),
                ("product_type", models.CharField(max_length=20)),
                ("location_code", models.CharField(max_length=10)),
                ("warehouse_status", models.CharField(max_length=10)),
                ("entry_time", models.DateTimeField()),
                ("trace_code", models.CharField(max_length=16)),
            ],
            options={
                "db_table": "warehouse_stock",
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "flow_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("type", models.CharField(max_length=10)),
                ("source", models.CharField(max_length=20)),
                ("destination", models.CharField(max_length=20)),
                ("operator", models.CharField(max_length=20)),
                ("time", models.DateTimeField()),
                (
                    "batch_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stock.warehousestock",
                    ),
                ),
            ],
            options={
                "db_table": "stock_movement",
            },
        ),
        migrations.CreateModel(
            name="InventoryCheck",
            fields=[
                (
                    "check_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("product_id", models.CharField(max_length=8)),
                ("recorded_quantity", models.FloatField()),
                ("actual_quantity", models.FloatField()),
                ("check_time", models.DateTimeField()),
                ("checker", models.CharField(max_length=20)),
                (
                    "batch_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stock.warehousestock",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_check",
            },
        ),
        migrations.CreateModel(
            name="BatchQualityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issue", models.TextField()),
                ("report_time", models.DateTimeField()),
                ("reporter", models.CharField(max_length=8)),
                ("action_taken", models.TextField()),
                (
                    "batch_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stock.warehousestock",
                    ),
                ),
            ],
            options={
                "db_table": "batch_quality_log",
            },
        ),
    ]
