# Generated by Django 5.2.1 on 2025-06-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FinancialFlows",
            fields=[
                (
                    "flow_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("type", models.CharField(max_length=10)),
                ("source_id", models.CharField(max_length=8)),
                ("amount", models.FloatField()),
                ("reason", models.TextField()),
                ("time", models.DateTimeField()),
            ],
            options={
                "db_table": "financial_flows",
            },
        ),
        migrations.CreateModel(
            name="PurchasePayment",
            fields=[
                (
                    "flow_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("purchase_id", models.CharField(max_length=8)),
                ("amount", models.FloatField()),
                ("pay_time", models.DateTimeField()),
            ],
            options={
                "db_table": "purchase_payment",
            },
        ),
        migrations.CreateModel(
            name="ReimbursementRequests",
            fields=[
                (
                    "reimbursement_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("applicant_id", models.CharField(max_length=8)),
                ("department", models.CharField(max_length=20)),
                ("amount", models.FloatField()),
                ("reason", models.TextField()),
                ("status", models.CharField(max_length=20)),
                ("submit_time", models.DateTimeField()),
                ("audit_time", models.DateTimeField(blank=True, null=True)),
                ("auditor_id", models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                "db_table": "reimbursement_requests",
            },
        ),
        migrations.CreateModel(
            name="SalesPayment",
            fields=[
                (
                    "flow_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("order_id", models.CharField(max_length=8)),
                ("amount", models.FloatField()),
                ("pay_time", models.DateTimeField()),
            ],
            options={
                "db_table": "sales_payment",
            },
        ),
    ]
