# Generated by Django 5.2.1 on 2025-06-06 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customers",
            fields=[
                (
                    "customer_id",
                    models.CharField(max_length=8, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=30)),
                ("phone", models.CharField(max_length=11)),
                ("address", models.TextField()),
            ],
            options={
                "db_table": "customers",
            },
        ),
        migrations.CreateModel(
            name="SalesOrders",
            fields=[
                (
                    "order_id",
                    models.CharField(max_length=8, primary_key=True, serialize=False),
                ),
                ("total_price", models.FloatField()),
                ("order_time", models.DateTimeField()),
                ("delivery_id", models.CharField(blank=True, max_length=8, null=True)),
                (
                    "customer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sale.customers"
                    ),
                ),
            ],
            options={
                "db_table": "sales_orders",
            },
        ),
        migrations.CreateModel(
            name="SalesItems",
            fields=[
                (
                    "item_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("product_id", models.CharField(max_length=8)),
                ("batch_id", models.CharField(max_length=12)),
                ("unit_price", models.FloatField()),
                ("quantity", models.FloatField()),
                (
                    "order_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sale.salesorders",
                    ),
                ),
            ],
            options={
                "db_table": "sales_items",
            },
        ),
    ]
