# Generated by Django 5.2.1 on 2025-06-06 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeliveryTasks",
            fields=[
                (
                    "delivery_id",
                    models.CharField(max_length=8, primary_key=True, serialize=False),
                ),
                ("order_id", models.CharField(max_length=8)),
                ("driver_id", models.CharField(max_length=8)),
                ("departure_time", models.DateTimeField()),
                ("arrival_time", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "delivery_tasks",
            },
        ),
        migrations.CreateModel(
            name="DeliveryItems",
            fields=[
                (
                    "item_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("product_id", models.CharField(max_length=8)),
                ("batch_id", models.CharField(max_length=12)),
                ("quantity", models.FloatField()),
                (
                    "delivery_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="deliver.deliverytasks",
                    ),
                ),
            ],
            options={
                "db_table": "delivery_items",
            },
        ),
        migrations.CreateModel(
            name="DispatchOrders",
            fields=[
                (
                    "dispatch_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("assigned_by", models.CharField(max_length=8)),
                ("assigned_time", models.DateTimeField()),
                ("status", models.CharField(max_length=20)),
                (
                    "delivery_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="deliver.deliverytasks",
                    ),
                ),
            ],
            options={
                "db_table": "dispatch_orders",
            },
        ),
        migrations.CreateModel(
            name="TemperatureLog",
            fields=[
                (
                    "log_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("time", models.DateTimeField()),
                ("temperature", models.FloatField()),
                ("gps_location", models.CharField(max_length=50)),
                (
                    "delivery_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="deliver.deliverytasks",
                    ),
                ),
            ],
            options={
                "db_table": "temperature_log",
            },
        ),
    ]
