# Generated by Django 5.2.1 on 2025-06-06 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AfterSalesRequests",
            fields=[
                (
                    "request_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("order_id", models.CharField(max_length=8)),
                ("customer_id", models.CharField(max_length=8)),
                ("request_time", models.DateTimeField()),
                ("status", models.CharField(max_length=20)),
                ("reason", models.TextField()),
            ],
            options={
                "db_table": "after_sales_requests",
            },
        ),
        migrations.CreateModel(
            name="AfterSalesItems",
            fields=[
                (
                    "item_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("product_id", models.CharField(max_length=8)),
                ("batch_id", models.CharField(max_length=12)),
                ("quantity", models.FloatField()),
                ("handling_result", models.TextField()),
                (
                    "request_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aftermarket.aftersalesrequests",
                    ),
                ),
            ],
            options={
                "db_table": "after_sales_items",
            },
        ),
        migrations.CreateModel(
            name="AfterSalesResolution",
            fields=[
                (
                    "resolution_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("decision", models.CharField(max_length=20)),
                ("decision_by", models.CharField(max_length=8)),
                ("decision_time", models.DateTimeField()),
                ("refund_id", models.CharField(max_length=10)),
                ("notes", models.TextField()),
                (
                    "request_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aftermarket.aftersalesrequests",
                    ),
                ),
            ],
            options={
                "db_table": "after_sales_resolution",
            },
        ),
    ]
