# Generated by Django 5.2.1 on 2025-06-06 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TraceCodes",
            fields=[
                (
                    "trace_code",
                    models.CharField(max_length=16, primary_key=True, serialize=False),
                ),
                ("product_id", models.CharField(max_length=8)),
                ("batch_id", models.CharField(max_length=12)),
                ("create_time", models.DateTimeField()),
            ],
            options={
                "db_table": "trace_codes",
            },
        ),
        migrations.CreateModel(
            name="TraceEvents",
            fields=[
                (
                    "event_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("event_type", models.CharField(max_length=20)),
                ("timestamp", models.DateTimeField()),
                ("actor", models.CharField(max_length=20)),
                ("detail", models.TextField()),
                (
                    "trace_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Traceability.tracecodes",
                    ),
                ),
            ],
            options={
                "db_table": "trace_events",
            },
        ),
    ]
