# Generated by Django 5.2.1 on 2025-06-06 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PurchaseItems",
            fields=[
                (
                    "item_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("product_id", models.CharField(max_length=8)),
                ("quantity", models.FloatField()),
                ("unit_price", models.FloatField()),
                ("batch_id", models.CharField(max_length=12)),
                ("trace_code", models.CharField(max_length=16)),
            ],
            options={
                "db_table": "purchase_items",
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrders",
            fields=[
                (
                    "purchase_id",
                    models.CharField(max_length=8, primary_key=True, serialize=False),
                ),
                ("order_time", models.DateTimeField()),
                ("expected_arrival", models.DateTimeField()),
                ("order_status", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "purchase_orders",
            },
        ),
        migrations.CreateModel(
            name="PurchaseRequests",
            fields=[
                (
                    "request_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("product_id", models.CharField(max_length=8)),
                ("request_quantity", models.FloatField()),
                ("request_time", models.DateTimeField()),
                ("request_by", models.CharField(max_length=8)),
                ("status", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "purchase_requests",
            },
        ),
        migrations.CreateModel(
            name="Suppliers",
            fields=[
                (
                    "supplier_id",
                    models.CharField(max_length=8, primary_key=True, serialize=False),
                ),
                ("supplier_name", models.CharField(max_length=50)),
                ("address", models.TextField()),
                ("contact_name", models.CharField(max_length=20)),
                ("contact_phone", models.CharField(max_length=11)),
            ],
            options={
                "db_table": "suppliers",
            },
        ),
        migrations.CreateModel(
            name="PurchaseAcceptance",
            fields=[
                (
                    "acceptance_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("arrival_time", models.DateTimeField()),
                ("accepted_quantity", models.FloatField()),
                ("inspection_result", models.CharField(max_length=20)),
                ("inspector", models.CharField(max_length=20)),
                ("batch_id", models.CharField(max_length=12)),
                (
                    "item_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="buy.purchaseitems",
                    ),
                ),
            ],
            options={
                "db_table": "purchase_acceptance",
            },
        ),
        migrations.AddField(
            model_name="purchaseitems",
            name="purchase_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="buy.purchaseorders"
            ),
        ),
        migrations.AddField(
            model_name="purchaseorders",
            name="supplier_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="buy.suppliers"
            ),
        ),
        migrations.CreateModel(
            name="SupplierStatusLog",
            fields=[
                (
                    "log_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("status", models.CharField(max_length=20)),
                ("reason", models.TextField()),
                ("timestamp", models.DateTimeField()),
                (
                    "supplier_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="buy.suppliers"
                    ),
                ),
            ],
            options={
                "db_table": "supplier_status_log",
            },
        ),
    ]
